name: docker-build-publish
on: [push]
jobs:
  publish-mattermost-arm64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code  
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      run: |
        docker build . --file Dockerfile --tag wekan:latest
        docker push ghcr.io/${{ github.repository_owner }}/wekan:latest